### PR TITLE
pants: upgrade Pants to 2.18.0

### PR DESCRIPTION
**Pull request by AlexTereshenkov**

### CODE REVIEW

**Comment by benjyw** [comment]
This will fail on M1s. We need to wait for a 2.18.1 with https://github.com/pantsbuild/pants/pull/20194, and then also switch to temurin JVMs, as in https://github.com/pantsbuild/example-jvm/pull/29/files

**Comment by huonw** [comment]
I've confirmed that `pants test ::` and `pants package ::` work on arm macOS, with https://github.com/pantsbuild/pants/releases/tag/release_2.18.1rc0 and the change to temurin JVM.

**Comment by AlexTereshenkov** [comment]
Thanks for confirming, I'll be back once 2.18.1 is out.

**Comment by huonw** [comment]
https://github.com/pantsbuild/pants/releases/tag/release_2.18.1 is out!

**Comment by huonw** [comment]
Replaced by https://github.com/pantsbuild/example-kotlin/pull/15

**Pull request closed without merging**
