### PR TITLE
add JSON serialization example for Kotlin

### PR DESCRIPTION
**Pull request by tdyas**
Add a contrived example of using the Kotlin Serialization plugin to encode and decode JSON data.

### CODE REVIEW

**Comment by tdyas** [comment]
Note: I pushed `pants.toml` directly to `main` as the initial commit. Probably worth reviewing `pants.toml` as well despite it not being in this PR.

**Review by Eric-Arellano — APPROVED** [review]
Thanks!

**Comment by tdyas** [comment]
CI failure:

```
  ClasspathRootOnlyWasInner: The following targets had dependees, but can only be used as roots in a build graph:
  * src/jvm/org/pantsbuild/example/json/JsonExample.kt	(kotlin_source)
```

https://github.com/pantsbuild/example-kotlin/runs/6438158675?check_suite_focus=true#step:6:11

@stuhood / @chrisjrn:  Thoughts on this failure? `kotlin_source` is not marked as root only. Only `deploy_jar` is marked with `root_only=True`.

**Comment by tdyas** [comment]
> > CI failure:
> > ```
> >   ClasspathRootOnlyWasInner: The following targets had dependees, but can only be used as roots in a build graph:
> >   * src/jvm/org/pantsbuild/example/json/JsonExample.kt	(kotlin_source)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/pantsbuild/example-kotlin/runs/6438158675?check_suite_focus=true#step:6:11
> > @stuhood / @chrisjrn: Thoughts on this failure? `kotlin_source` is not marked as root only. Only `deploy_jar` is marked with `root_only=True`. (Technically the `ClasspathEntryRequest` being marked.)
> 
> Bug...
> 
> It looks like this code is looking at a loop variable: https://github.com/pantsbuild/pants/blob/43a3ab258f36e74a84ea2b2091c5a374259677d4/src/python/pants/jvm/compile.py#L121-L125

Good eyes!

**Comment by tdyas** [comment]
https://github.com/pantsbuild/pants/pull/15494 appears to fix the issue.

**Review by Eric-Arellano — APPROVED** [review]

**Pull request merged**
